const restaurantData = {
  restaurants: [
    {
      id: 1,
      name: "The Gourmet Bistro",
      location: {
        address: "123 Main St",
        city: "New Orleans",
        state: "LA",
        zip: "70112",
      },
      cuisine: "French",
      rating: 4.8,
      priceRange: "$$$$",
    },
    {
      id: 2,
      name: "Mama Mia's Pizzeria",
      location: {
        address: "456 Oak St",
        city: "Baton Rouge",
        state: "LA",
        zip: "70802",
      },
      cuisine: "Italian",
      rating: 4.3,
      priceRange: "$$",
    },
    {
      id: 3,
      name: "Sushi Haven",
      location: {
        address: "789 Elm St",
        city: "Shreveport",
        state: "LA",
        zip: "71101",
      },
      cuisine: "Japanese",
      rating: 4.6,
      priceRange: "$$$",
    },
    {
      id: 4,
      name: "Burger Town",
      location: {
        address: "321 Maple Ave",
        city: "Lafayette",
        state: "LA",
        zip: "70501",
      },
      cuisine: "American",
      rating: 4.2,
      priceRange: "$$",
    },
    {
      id: 5,
      name: "Spice Route",
      location: {
        address: "654 Pine St",
        city: "Lake Charles",
        state: "LA",
        zip: "70601",
      },
      cuisine: "Indian",
      rating: 4.5,
      priceRange: "$$$",
    },
    {
      id: 6,
      name: "Taco Fiesta",
      location: {
        address: "987 Cedar Blvd",
        city: "Alexandria",
        state: "LA",
        zip: "71301",
      },
      cuisine: "Mexican",
      rating: 4.1,
      priceRange: "$",
    },
    {
      id: 7,
      name: "Green Garden",
      location: {
        address: "159 Oak St",
        city: "Monroe",
        state: "LA",
        zip: "71201",
      },
      cuisine: "Vegetarian",
      rating: 4.7,
      priceRange: "$$$",
    },
    {
      id: 8,
      name: "BBQ Nation",
      location: {
        address: "753 Birch Ln",
        city: "Houma",
        state: "LA",
        zip: "70360",
      },
      cuisine: "BBQ",
      rating: 4.4,
      priceRange: "$$",
    },
    {
      id: 9,
      name: "The Seafood Shack",
      location: {
        address: "852 Water St",
        city: "Metairie",
        state: "LA",
        zip: "70001",
      },
      cuisine: "Seafood",
      rating: 4.3,
      priceRange: "$$$",
    },
    {
      id: 10,
      name: "Pasta Palace",
      location: {
        address: "741 Olive St",
        city: "Kenner",
        state: "LA",
        zip: "70062",
      },
      cuisine: "Italian",
      rating: 4.5,
      priceRange: "$$$",
    },
    {
      id: 11,
      name: "Curry Corner",
      location: {
        address: "159 Spruce St",
        city: "Bossier City",
        state: "LA",
        zip: "71111",
      },
      cuisine: "Indian",
      rating: 4.6,
      priceRange: "$$$",
    },
    {
      id: 12,
      name: "Creole Kitchen",
      location: {
        address: "321 River Rd",
        city: "New Orleans",
        state: "LA",
        zip: "70130",
      },
      cuisine: "Creole",
      rating: 4.7,
      priceRange: "$$$",
    },
    {
      id: 13,
      name: "Pho Paradise",
      location: {
        address: "123 Bamboo St",
        city: "Slidell",
        state: "LA",
        zip: "70458",
      },
      cuisine: "Vietnamese",
      rating: 4.4,
      priceRange: "$$",
    },
    {
      id: 14,
      name: "Dragon House",
      location: {
        address: "654 Dragonfly Ln",
        city: "Gretna",
        state: "LA",
        zip: "70053",
      },
      cuisine: "Chinese",
      rating: 4.2,
      priceRange: "$$",
    },
    {
      id: 15,
      name: "Steakhouse Grill",
      location: {
        address: "789 Pepper St",
        city: "Covington",
        state: "LA",
        zip: "70433",
      },
      cuisine: "Steakhouse",
      rating: 4.8,
      priceRange: "$$$$",
    },
    {
      id: 16,
      name: "Mediterranean Delight",
      location: {
        address: "321 Sun St",
        city: "Mandeville",
        state: "LA",
        zip: "70448",
      },
      cuisine: "Mediterranean",
      rating: 4.5,
      priceRange: "$$$",
    },
    {
      id: 17,
      name: "Burger Joint",
      location: {
        address: "753 Palm St",
        city: "Thibodaux",
        state: "LA",
        zip: "70301",
      },
      cuisine: "American",
      rating: 4.1,
      priceRange: "$",
    },
    {
      id: 18,
      name: "Tandoori Grill",
      location: {
        address: "456 Jasmine St",
        city: "Lafayette",
        state: "LA",
        zip: "70503",
      },
      cuisine: "Indian",
      rating: 4.3,
      priceRange: "$$$",
    },
    {
      id: 19,
      name: "Sushi Express",
      location: {
        address: "987 Tulip Ln",
        city: "Ruston",
        state: "LA",
        zip: "71270",
      },
      cuisine: "Japanese",
      rating: 4.6,
      priceRange: "$$$",
    },
    {
      id: 20,
      name: "Bistro on the Bay",
      location: {
        address: "159 Harbor Dr",
        city: "Lake Charles",
        state: "LA",
        zip: "70605",
      },
      cuisine: "French",
      rating: 4.7,
      priceRange: "$$$$",
    },
  ],
};

export default restaurantData;
