const restaurantData = {
  restaurants: [
    {
      id: 1,
      name: "The Gourmet Bistro",
      location: {
        address: "123 Main St",
        city: "New Orleans",
        state: "LA",
        zip: "70112",
      },
      cuisine: "French",
      rating: 4.8,
      priceRange: "$$$$",
      imageUrl: "https://images.unsplash.com/photo-1555992336-03a23f34ebc1",
      website: "https://www.gourmetbistro.com",
    },
    {
      id: 2,
      name: "Mama Mia's Pizzeria",
      location: {
        address: "456 Oak St",
        city: "Baton Rouge",
        state: "LA",
        zip: "70802",
      },
      cuisine: "Italian",
      rating: 4.3,
      priceRange: "$$",
      imageUrl: "https://images.unsplash.com/photo-1585238341863-1d1a5f980308",
      website: "https://www.mamamiaspizzeria.com",
    },
    {
      id: 3,
      name: "Sushi Haven",
      location: {
        address: "789 Elm St",
        city: "Shreveport",
        state: "LA",
        zip: "71101",
      },
      cuisine: "Japanese",
      rating: 4.6,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1562967916-eb82221dfb53",
      website: "https://www.sushihaven.com",
    },
    {
      id: 4,
      name: "Burger Town",
      location: {
        address: "321 Maple Ave",
        city: "Lafayette",
        state: "LA",
        zip: "70501",
      },
      cuisine: "American",
      rating: 4.2,
      priceRange: "$$",
      imageUrl: "",
      website: "https://www.burgertown.com",
    },
    {
      id: 5,
      name: "Spice Route",
      location: {
        address: "654 Pine St",
        city: "Lake Charles",
        state: "LA",
        zip: "70601",
      },
      cuisine: "Indian",
      rating: 4.5,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1592194996308-7d4a2bb69130",
      website: "https://www.spiceroute.com",
    },
    {
      id: 6,
      name: "Taco Fiesta",
      location: {
        address: "987 Cedar Blvd",
        city: "Alexandria",
        state: "LA",
        zip: "71301",
      },
      cuisine: "Mexican",
      rating: 4.1,
      priceRange: "$",
      imageUrl: "",
      website: "https://www.tacofiesta.com",
    },
    {
      id: 7,
      name: "Green Garden",
      location: {
        address: "159 Oak St",
        city: "Monroe",
        state: "LA",
        zip: "71201",
      },
      cuisine: "Vegetarian",
      rating: 4.7,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1600203780319-26a4ce1f64d9",
      website: "https://www.greengarden.com",
    },
    {
      id: 8,
      name: "BBQ Nation",
      location: {
        address: "753 Birch Ln",
        city: "Houma",
        state: "LA",
        zip: "70360",
      },
      cuisine: "BBQ",
      rating: 4.4,
      priceRange: "$$",
      imageUrl: "https://images.unsplash.com/photo-1592928300483-11b64437579d",
      website: "https://www.bbqnation.com",
    },
    {
      id: 9,
      name: "The Seafood Shack",
      location: {
        address: "852 Water St",
        city: "Metairie",
        state: "LA",
        zip: "70001",
      },
      cuisine: "Seafood",
      rating: 4.3,
      priceRange: "$$$",
      imageUrl: "",
      website: "https://www.seafoodshack.com",
    },
    {
      id: 10,
      name: "Pasta Palace",
      location: {
        address: "741 Olive St",
        city: "Kenner",
        state: "LA",
        zip: "70062",
      },
      cuisine: "Italian",
      rating: 4.5,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1601924549205-0d6b14d4d3b2",
      website: "https://www.pastapalace.com",
    },
    {
      id: 11,
      name: "Curry Corner",
      location: {
        address: "159 Spruce St",
        city: "Bossier City",
        state: "LA",
        zip: "71111",
      },
      cuisine: "Indian",
      rating: 4.6,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1568302229440-469dd2d78b76",
      website: "https://www.currycorner.com",
    },
    {
      id: 12,
      name: "Creole Kitchen",
      location: {
        address: "321 River Rd",
        city: "New Orleans",
        state: "LA",
        zip: "70130",
      },
      cuisine: "Creole",
      rating: 4.7,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1622819947306-8408fc8a1b0b",
      website: "https://www.creolekitchen.com",
    },
    {
      id: 13,
      name: "Pho Paradise",
      location: {
        address: "123 Bamboo St",
        city: "Slidell",
        state: "LA",
        zip: "70458",
      },
      cuisine: "Vietnamese",
      rating: 4.4,
      priceRange: "$$",
      imageUrl: "https://images.unsplash.com/photo-1597473048861-bc68a55202dd",
      website: "https://www.phoparadise.com",
    },
    {
      id: 14,
      name: "Dragon House",
      location: {
        address: "654 Dragonfly Ln",
        city: "Gretna",
        state: "LA",
        zip: "70053",
      },
      cuisine: "Chinese",
      rating: 4.2,
      priceRange: "$$",
      imageUrl: "https://images.unsplash.com/photo-1608215683116-2d3a4ec546d9",
      website: "https://www.dragonhouse.com",
    },
    {
      id: 15,
      name: "Steakhouse Grill",
      location: {
        address: "789 Pepper St",
        city: "Covington",
        state: "LA",
        zip: "70433",
      },
      cuisine: "Steakhouse",
      rating: 4.8,
      priceRange: "$$$$",
      imageUrl: "https://images.unsplash.com/photo-1593759608988-6b499e4c1b1f",
      website: "https://www.steakhousegrill.com",
    },
    {
      id: 16,
      name: "Mediterranean Delight",
      location: {
        address: "321 Sun St",
        city: "Mandeville",
        state: "LA",
        zip: "70448",
      },
      cuisine: "Mediterranean",
      rating: 4.5,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1586880244404-b7b85061d54f",
      website: "https://www.mediterraneandelight.com",
    },
    {
      id: 17,
      name: "Burger Joint",
      location: {
        address: "753 Palm St",
        city: "Thibodaux",
        state: "LA",
        zip: "70301",
      },
      cuisine: "American",
      rating: 4.1,
      priceRange: "$",
      imageUrl: "https://images.unsplash.com/photo-1606755962779-99e3c5f384b7",
      website: "https://www.burgerjoint.com",
    },
    {
      id: 18,
      name: "Tandoori Grill",
      location: {
        address: "456 Jasmine St",
        city: "Lafayette",
        state: "LA",
        zip: "70503",
      },
      cuisine: "Indian",
      rating: 4.3,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1622921358045-71e05b64ea3c",
      website: "https://www.tandoorigrill.com",
    },
    {
      id: 19,
      name: "Sushi Express",
      location: {
        address: "987 Tulip Ln",
        city: "Ruston",
        state: "LA",
        zip: "71270",
      },
      cuisine: "Japanese",
      rating: 4.6,
      priceRange: "$$$",
      imageUrl: "https://images.unsplash.com/photo-1602980234431-9b2c8aa80527",
      website: "https://www.sushiexpress.com",
    },
    {
      id: 20,
      name: "Bistro on the Bay",
      location: {
        address: "159 Harbor Dr",
        city: "Lake Charles",
        state: "LA",
        zip: "70605",
      },
      cuisine: "French",
      rating: 4.7,
      priceRange: "$$$$",
      imageUrl: "https://images.unsplash.com/photo-1609990131926-753ef3780ab7",
      website: "https://www.bistroonthebay.com",
    },
  ],
};

export default restaurantData;
